//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceTypeParameter
    {
        public int resourceTypeParameterID { get; set; }
        public int resourceTypeID { get; set; }
        public int parameterID { get; set; }
        public int companyID { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblParameter tblParameter { get; set; }
        public virtual tblResourceType tblResourceType { get; set; }
    }
}
