//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResourceType()
        {
            this.tblResources = new HashSet<tblResource>();
            this.tblResourceTypeParameters = new HashSet<tblResourceTypeParameter>();
        }
    
        public int resourceTypeID { get; set; }
        public string resourceTypeName { get; set; }
        public string resourceTypeDescription { get; set; }
        public int parameterCount { get; set; }
        public string separator { get; set; }
        public int companyID { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResource> tblResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResourceTypeParameter> tblResourceTypeParameters { get; set; }
    }
}
