//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParameter()
        {
            this.tblResourceTypeParameters = new HashSet<tblResourceTypeParameter>();
            this.tblSheets = new HashSet<tblSheet>();
        }
    
        public int parameterID { get; set; }
        public string parameterName { get; set; }
        public string parameterUnit { get; set; }
        public Nullable<double> parameterMinThr { get; set; }
        public Nullable<double> parameterMaxThr { get; set; }
        public int companyID { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResourceTypeParameter> tblResourceTypeParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSheet> tblSheets { get; set; }
    }
}
