//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubResource
    {
        public int subResourceID { get; set; }
        public string subResourceName { get; set; }
        public string subResourceLocationName { get; set; }
        public string subResourceDescription { get; set; }
        public string subResourceCode { get; set; }
        public string subResourceNumber { get; set; }
        public string subResourceGeoLocatin { get; set; }
        public int resourceID { get; set; }
        public int companyID { get; set; }
        public Nullable<int> subResourceStatus { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblResource tblResource { get; set; }
    }
}
