//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public tblCompany()
        {
            this.tblParameters = new HashSet<tblParameter>();
            this.tblResources = new HashSet<tblResource>();
            this.tblResourceTypes = new HashSet<tblResourceType>();
            this.tblResourceTypeParameters = new HashSet<tblResourceTypeParameter>();
            this.tblSheets = new HashSet<tblSheet>();
            this.tblSubResources = new HashSet<tblSubResource>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string companyDescription { get; set; }
    
        public virtual ICollection<tblParameter> tblParameters { get; set; }
        public virtual ICollection<tblResource> tblResources { get; set; }
        public virtual ICollection<tblResourceType> tblResourceTypes { get; set; }
        public virtual ICollection<tblResourceTypeParameter> tblResourceTypeParameters { get; set; }
        public virtual ICollection<tblSheet> tblSheets { get; set; }
        public virtual ICollection<tblSubResource> tblSubResources { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
