//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wasaRms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResource
    {
        public tblResource()
        {
            this.tblSheets = new HashSet<tblSheet>();
        }
    
        public int resourceID { get; set; }
        public string resourceName { get; set; }
        public string resourceLocationName { get; set; }
        public string resourceDescription { get; set; }
        public string resourceCode { get; set; }
        public string resourceNumber { get; set; }
        public string resourceGeoLocatin { get; set; }
        public int resourceTypeID { get; set; }
        public int companyID { get; set; }
        public Nullable<int> resourceStatus { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblResourceType tblResourceType { get; set; }
        public virtual ICollection<tblSheet> tblSheets { get; set; }
        public virtual tblSubResource tblSubResource { get; set; }
    }
}
